/**
 * Utility to convert local image paths to Vercel Blob Storage URLs
 * 
 * This file imports the blob URL mapping generated by the upload script.
 * Team photos stored in blob storage will use blob URLs, while local images
 * will fall back to local paths.
 */

import blobUrlMapping from '../../../blob-url-mapping.json';

/**
 * Converts a local image path to a blob URL if it exists in blob storage,
 * otherwise returns the original local path as a fallback.
 * 
 * @param localPath - Local path like "/team/teamPhotos/john.webp"
 * @returns Blob URL if found, otherwise original local path
 * 
 * @example
 *   getBlobUrl("/team/teamPhotos/john.webp")
 *   // Returns: "https://xxx.public.blob.vercel-storage.com/team/teamPhotos/john.webp"
 *   
 *   getBlobUrl("/nonexistent/image.png")
 *   // Returns: "/nonexistent/image.png" (fallback to local)
 */
export function getBlobUrl(localPath: string): string {
  // check if the path exists in the blob mapping
  const mapping = blobUrlMapping as Record<string, { url: string; pathname: string }>;
  const blobInfo = mapping[localPath];

  if (blobInfo?.url) {
    return blobInfo.url;
  }

  // no fallback

}

