export const teamLeads = [
  {
    name: "Thomas Wells",
    subteam: "Hardware",
    classYear: "2027",
    hometown: "Lansing, NY",
    major: "Mechanical Engineering",
    linkedin: "https://www.linkedin.com/company/cornell-university-autoboat/",
    image: "/Thomas.png",
    portfolio: "https://www.cornellautoboat.com/", 
  },
  {
    name: "Neha Naveen",
    subteam: "Software",
    classYear: "2027",
    hometown: "California",
    major: "Computer Science",
    linkedin: "https://www.linkedin.com/company/cornell-university-autoboat/",
    image: "/Neha.png",
    portfolio: "https://www.cornellautoboat.com/", 
  },
];
export const hardware = [
  {
    name: "Rajarshi Das",
    subteam: "Robotics Lead",
    classYear: "2026",
    hometown: "Westbury, NY",
    major: "Mechanical Engineering",
    linkedin: "https://www.linkedin.com/company/cornell-university-autoboat/",
    image: "/ABteam2.jpg",
    portfolio: "https://www.cornellautoboat.com/", 
  },
  {
    name: "Findlay Hartman",
    subteam: "Manufacturing Lead",
    classYear: "2027",
    hometown: "Tampa, FL",
    major: "Materials Science & Engineering",
    linkedin: "https://www.linkedin.com/company/cornell-university-autoboat/",
    image: "/ABteam2.jpg",
    portfolio: "https://www.cornellautoboat.com/", 
  },
  {
    name: "Nitya Shukla",
    subteam: "Design Lead",
    classYear: "2027",
    hometown: "Briarcliff Manor, NY",
    major: "Mechanical Engineering",
    linkedin: "https://www.linkedin.com/company/cornell-university-autoboat/",
    image: "/ABteam2.jpg",
    portfolio: "https://www.cornellautoboat.com/", 
  },
  {
    name: "Daniel Yu",
    subteam: "E-Systems Lead",
    classYear: "2026",
    hometown: "Raritan, NJ",
    major: "Electrical & Computer Engineering",
    linkedin: "https://www.linkedin.com/company/cornell-university-autoboat/",
    image: "/ABteam2.jpg",
    portfolio: "https://www.cornellautoboat.com/", 
  },
  
];

